In [1]:
import torch

In [3]:
# 보통 계산을 위한 데이터
ft = torch.FloatTensor([[1,2],
[3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
# int형 숫자를 사용시
lt = torch.LongTensor([[1,2],[3,4]])
lt

tensor([[1., 2.],
        [3., 4.]])

In [7]:
# true/false 사용시 
bt = torch.ByteTensor([[1,0],[0,1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [6]:
x = torch.FloatTensor(3,2)
x

tensor([[0.0000e+00, 7.7071e-44],
        [8.4022e+20, 2.0315e+20],
        [1.3282e-08, 2.0547e+20]])

numpy compatibility

In [8]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [9]:
x = torch.from_numpy(x)
print(x,type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [10]:
x = x.numpy()
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


tensor Type-casting

In [11]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [12]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [13]:
torch.FloatTensor([1,0]).byte()

tensor([1, 0], dtype=torch.uint8)

Get Shape

In [15]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [16]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [17]:
print(x.dim())
print(len(x.size()))

3
3


In [19]:
print(x.size(1))
print(x.shape[1])

2
2


In [20]:
print(x.size(-1))
print(x.shape[-1])

2
2
