In [18]:
import torch

Arithmetic Element-wise Operations

In [19]:
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[2,2],[3,3]])

In [20]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [21]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [22]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [23]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [24]:
a == b

tensor([[False,  True],
        [ True, False]])

In [25]:
a != b

tensor([[ True, False],
        [False,  True]])

In [26]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

Inplace Operations

In [28]:
print(a)
print(b)
print('------------')
print(a.mul(b))
print(a)
print('------------')
print(a.mul_(b))
print(a)
print('------------')

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[2., 2.],
        [3., 3.]])
------------
tensor([[ 4.,  8.],
        [27., 36.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
------------
tensor([[ 4.,  8.],
        [27., 36.]])
tensor([[ 4.,  8.],
        [27., 36.]])
------------


Sum, Mean(Dimension Reducing Operations)

In [32]:
x = torch.FloatTensor([[1,2],[3,4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [30]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [31]:
print(x.sum(dim=0))  
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


Broadcast in Operations

In [33]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[4,8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [34]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


Tensor + Scalar

In [35]:
x = torch.FloatTensor([[1,2],[3,4]])
y = 1
print(x.size())

torch.Size([2, 2])


In [36]:
z =x + y
print(z)
print(z.size()) 

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


Tensor + Vector

In [37]:
x = torch.FloatTensor([[1,2],[4,8]])
y = torch.FloatTensor([3,5])
print(x)
print(y)
print(x.size())
print(y.size())

tensor([[1., 2.],
        [4., 8.]])
tensor([3., 5.])
torch.Size([2, 2])
torch.Size([2])


In [38]:
from tkinter import Y


z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [39]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [40]:
z = x + y 
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


Tensor + Tensor

In [43]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],[5]])

print(x.size())
print(y.size())

print(x)
print(y)

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[1., 2.]])
tensor([[3.],
        [5.]])


In [42]:
z = x + y 
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


Failure Case

In [45]:
x = torch.FloatTensor([[[1,2],[4,8]]])
y = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])

print(x.size())
print(y.size())

z = x + y

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2