In [1]:
import torch

In [8]:
x = torch.FloatTensor([[[1,2]],[[3,4]]])
print(x.size())
x

torch.Size([2, 1, 2])


tensor([[[1., 2.]],

        [[3., 4.]]])

In [6]:
y = x.expand(*[2,3,2])

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [7]:
y = torch.cat([x,x,x],dim=1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [9]:
x = torch.randperm(10)

print(x)
print(x.size())

tensor([1, 2, 5, 8, 0, 7, 3, 4, 6, 9])
torch.Size([10])


In [18]:
x = torch.randperm(3**3).reshape(3,3,-1)

print(x)
print(x.size())

tensor([[[16, 20,  1],
         [ 7, 11, 25],
         [ 3, 12, 14]],

        [[18, 22, 15],
         [19, 17,  2],
         [ 5, 10,  8]],

        [[ 0, 13, 21],
         [ 9,  6, 26],
         [24,  4, 23]]])
torch.Size([3, 3, 3])


In [23]:
y = x.argmax(dim=-1) # 해당 열에서 가장 큰 값의 인덱스를 반환

print(y)
print(y.size())

tensor([[1, 2, 2],
        [1, 0, 1],
        [2, 2, 0]])
torch.Size([3, 3])


In [25]:
print(x.size())

values, indices = torch.topk(x,k=1,dim=-1)

print(values.size())
print(indices.size())

torch.Size([3, 3, 3])
torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


In [29]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[20, 25, 14],
        [22, 19, 10],
        [21, 26, 24]])
tensor([[1, 2, 2],
        [1, 0, 1],
        [2, 2, 0]])
